repos:
-   repo: https://github.com/psf/black.git
    rev: 22.8.0  # Use the ref you want to point at
    hooks:
    - id: black

-   repo: https://github.com/pycqa/flake8.git
    rev: 5.0.4  # Use the ref you want to point at
    hooks:
    - id: flake8
