files: ^(app|src)/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
        args: [--unsafe]
  - repo: https://github.com/psf/black.git
    rev: 22.8.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/flake8.git
    rev: 5.0.4
    hooks:
    - id: flake8
      args: [--ignore=E501]
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.12.0
    hooks:
    - id: isort
      args: ['--profile', 'black']
