repos:
-   repo: https://github.com/psf/black.git
    rev: 21.6b0  # Use the ref you want to point at
    hooks:
    - id: black
      language_version: python3.9

-   repo: https://github.com/pycqa/flake8.git
    rev: 3.9.2  # Use the ref you want to point at
    hooks:
    - id: flake8
